name: CI/CD — analytics-service

on:
  push:
    branches: [main, pipeline-template]
  pull_request:
    branches: [main , pipeline-template]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  ci:
    uses: Pos-Tech-DevOps-DCLT/infra-tc4/.github/workflows/ci-cd-python-template.yaml@main
    with:
      project: analytics-service
    secrets: inherit